packages:
  - '.'

allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': true
  '@swc/core': true
  argon2: true
  msgpackr-extract: true

ignoredBuiltDependencies:
  - '@scarf/scarf'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - argon2
  - esbuild
