services:
  backend:
    container_name: aib-backend
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "6543:6543"
    depends_on:
      - redis
    networks:
      - aib-network

  redis:
    image: redis:7-alpine
    container_name: aib-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - aib-network

volumes:
  redis_data:

networks:
  aib-network:
    name: aib-network
    driver: bridge
