// Users
export {
  users,
  usersRelations,
  roleEnum,
  platformEnum,
  adminPermissionEnum,
} from './users';
export type { UserRow, NewUserRow } from './users';

// Auth
export {
  otps,
  otpsRelations,
  sessions,
  sessionsRelations,
  oauthAccounts,
  oauthAccountsRelations,
  usedTokens,
  usedTokensRelations,
} from './auth';
export type {
  OtpRow,
  NewOtpRow,
  SessionRow,
  NewSessionRow,
  OAuthAccountRow,
  NewOAuthAccountRow,
  UsedTokenRow,
  NewUsedTokenRow,
} from './auth';

// Client
export {
  clientAccounts,
  clientAccountsRelations,
  userStatusEnum,
  clientFavorites,
  clientFavoritesRelations,
  favoriteItemTypeEnum,
  clientWallets,
  clientWalletsRelations,
  clientWalletRecharges,
  clientWalletRechargesRelations,
  clientRechargeStatusEnum,
  clientTransactions,
  clientTransactionsRelations,
  clientTransactionTypeEnum,
  clientTransactionPurposeEnum,
} from './client';
export type {
  ClientAccountRow,
  NewClientAccountRow,
  ClientPreferences,
  ClientFavoriteRow,
  NewClientFavoriteRow,
  ClientWalletRow,
  NewClientWalletRow,
  ClientWalletRechargeRow,
  NewClientWalletRechargeRow,
  ClientTransactionRow,
  NewClientTransactionRow,
} from './client';

// Expert
export {
  expertAccounts,
  expertAccountsRelations,
  expertKycStatusEnum,
  specializations,
  specializationsRelations,
  professions,
  professionsRelations,
  professionSpecializations,
  professionSpecializationsRelations,
  expertSpecializations,
  expertSpecializationsRelations,
  expertProfessions,
  expertProfessionsRelations,
  expertConsultationPricing,
  expertConsultationPricingRelations,
  expertPricingTargetAudienceEnum,
  expertPricingStatusEnum,
  expertAstrologyServices,
  expertAstrologyServicesRelations,
  expertProducts,
  expertProductsRelations,
  expertProductRelationTypeEnum,
} from './expert';
export type {
  ExpertAccountRow,
  NewExpertAccountRow,
  SpecializationRow,
  NewSpecializationRow,
  ProfessionRow,
  NewProfessionRow,
  ProfessionSpecializationRow,
  NewProfessionSpecializationRow,
  ExpertSpecializationRow,
  NewExpertSpecializationRow,
  ExpertProfessionRow,
  NewExpertProfessionRow,
  ExpertConsultationPricingRow,
  NewExpertConsultationPricingRow,
  ExpertAstrologyServiceRow,
  NewExpertAstrologyServiceRow,
  ExpertProductRow,
  NewExpertProductRow,
} from './expert';

// Commerce
export {
  products,
  productsRelations,
  productTypeEnum,
  productGroupEnum,
  productVariants,
  productVariantsRelations,
  carts,
  cartsRelations,
  cartItems,
  cartItemsRelations,
  orders,
  ordersRelations,
  orderStatusEnum,
  orderPaymentStatusEnum,
  orderItems,
  orderItemsRelations,
  orderItemStatusEnum,
  orderShipments,
  orderShipmentsRelations,
  shipmentStatusEnum,
  orderAddresses,
  orderAddressesRelations,
  orderAddressTypeEnum,
  orderPayments,
  orderPaymentsRelations,
  paymentTransactionStatusEnum,
  orderRefunds,
  orderRefundsRelations,
  refundDestinationEnum,
  refundStatusEnum,
  productCategories,
  productVariantPricing,
  productVariantPricingRelations,
  variantPricingAudienceEnum,
  variantPricingStatusEnum,
  productVariantMedia,
  productVariantMediaRelations,
  variantMediaRoleEnum,
  productVariantPromotions,
  productVariantPromotionsRelations,
  promotionDiscountTypeEnum,
  promotionAudienceEnum,
  productVariantFulfillment,
  productVariantFulfillmentRelations,
  fulfillmentTypeEnum,
  deliveryTypeEnum,
  productVariantInventory,
  productVariantInventoryRelations,
  coupons,
  couponsRelations,
  couponTypeEnum,
  couponStatusEnum,
  userCoupons,
  userCouponsRelations,
  wishlists,
  wishlistsRelations,
} from './commerce';
export type {
  ProductRow,
  NewProductRow,
  ProductVariantRow,
  CartRow,
  NewCartRow,
  CartItemRow,
  NewCartItemRow,
  OrderRow,
  NewOrderRow,
  OrderStatusHistoryEntry,
  OrderItemRow,
  NewOrderItemRow,
  OrderShipmentRow,
  NewOrderShipmentRow,
  OrderAddressRow,
  NewOrderAddressRow,
  OrderPaymentRow,
  NewOrderPaymentRow,
  OrderRefundRow,
  NewOrderRefundRow,
  ProductCategoryRow,
  NewProductCategoryRow,
  ProductVariantPricingRow,
  NewProductVariantPricingRow,
  ProductVariantMediaRow,
  NewProductVariantMediaRow,
  ProductVariantPromotionRow,
  NewProductVariantPromotionRow,
  ProductVariantFulfillmentRow,
  NewProductVariantFulfillmentRow,
  ProductVariantInventoryRow,
  NewProductVariantInventoryRow,
  CouponRow,
  NewCouponRow,
  UserCouponRow,
  NewUserCouponRow,
  WishlistRow,
  NewWishlistRow,
} from './commerce';

// Addresses
export {
  addresses,
  addressesRelations,
  addressTypeEnum,
  addressTagEnum,
} from './addresses';
export type { AddressRow, NewAddressRow } from './addresses';

// Media
export { media, mediaSourceEnum } from './media';
export type { MediaRow, NewMediaRow } from './media';

// Support
export {
  notifications,
  notificationsRelations,
  notificationTypeEnum,
  NotificationType,
} from './support';
export type { NotificationRow, NewNotificationRow } from './support';

// Consultation
export {
  callSessions,
  callSessionsRelations,
  callSessionStatusEnum,
  callSessionTypeEnum,
  chatSessions,
  chatSessionsRelations,
  chatSessionStatusEnum,
  chatMessages,
  chatMessagesRelations,
  chatMessageTypeEnum,
  consultationTopics,
  consultations,
  consultationsRelations,
  consultationsModeEnum,
  consultationsStatusEnum,
  consultationSessions,
  consultationSessionsRelations,
  consultationSessionsStatusEnum,
  consultationSessionsModeEnum,
  sessionProviders,
  sessionProvidersRelations,
  sessionRecordings,
  sessionRecordingsRelations,
  sessionRecordingsStatusEnum,
  consultationMessages,
  consultationMessagesRelations,
  consultationMessagesTypeEnum,
  consultationMessageAttachments,
  consultationMessageAttachmentsRelations,
  consultationBillings,
  consultationBillingsRelations,
  consultationBillingsStatusEnum,
  reviews,
  reviewsRelations,
} from './consultation';
export type {
  CallSessionRow,
  NewCallSessionRow,
  ChatSessionRow,
  NewChatSessionRow,
  ChatMessageRow,
  NewChatMessageRow,
  ConsultationTopicRow,
  NewConsultationTopicRow,
  ConsultationRow,
  NewConsultationRow,
  ConsultationSessionRow,
  NewConsultationSessionRow,
  SessionProviderRow,
  NewSessionProviderRow,
  SessionRecordingRow,
  NewSessionRecordingRow,
  ConsultationMessageRow,
  NewConsultationMessageRow,
  ConsultationMessageAttachmentRow,
  NewConsultationMessageAttachmentRow,
  ConsultationBillingRow,
  NewConsultationBillingRow,
  ReviewRow,
  NewReviewRow,
} from './consultation';

// Merchant
export {
  merchantAccounts,
  merchantAccountsRelations,
  merchantStatusEnum,
  MerchantStatus,
} from './merchant';
export type { MerchantAccountRow, NewMerchantAccountRow } from './merchant';

// Finance
export {
  // Wallet
  wallets,
  walletsRelations,
  transactions,
  transactionsRelations,
  financeTransactionTypeEnum,
  financeTransactionPurposeEnum,
  withdrawals,
  withdrawalsRelations,
  withdrawalStatusEnum,
  idempotencyKeys,
  idempotencyKeysRelations,
  // Payments
  gatewayTransactions,
  gatewayTransactionsRelations,
  gatewayNameEnum,
  gatewayTransactionStatusEnum,
  gatewayIntentEnum,
  paymentOrders,
  paymentOrdersRelations,
  paymentOrderStatusEnum,
  // Commissions
  commissionRules,
  commissionRulesRelations,
  commissionEventTypeEnum,
  commissionTypeEnum,
  commissionRateTypeEnum,
  commissionAppliesRoleEnum,
  commissionTiers,
  commissionTiersRelations,
  commissionSplits,
  commissionSplitsRelations,
  splitReferenceTypeEnum,
  // Earnings
  earningPolicies,
  earningPoliciesRelations,
  earningEventTypeEnum,
  earningRateTypeEnum,
  earningAppliesRoleEnum,
  earningTiers,
  earningTiersRelations,
  earningSplits,
  earningSplitsRelations,
  // Ledger
  generalLedger,
  generalLedgerEntryTypeEnum,
  generalLedgerPartyTypeEnum,
  generalLedgerEventTypeEnum,
} from './finance';
export type {
  WalletRow,
  NewWalletRow,
  WalletKey,
  TransactionRow,
  NewTransactionRow,
  WithdrawalRow,
  NewWithdrawalRow,
  IdempotencyKeyRow,
  NewIdempotencyKeyRow,
  GatewayTransactionRow,
  NewGatewayTransactionRow,
  PaymentOrderRow,
  NewPaymentOrderRow,
  CommissionRuleRow,
  NewCommissionRuleRow,
  CommissionTierRow,
  NewCommissionTierRow,
  CommissionSplitRow,
  NewCommissionSplitRow,
  EarningPolicyRow,
  NewEarningPolicyRow,
  EarningTierRow,
  NewEarningTierRow,
  EarningSplitRow,
  NewEarningSplitRow,
  GeneralLedgerEntryRow,
  NewGeneralLedgerEntryRow,
} from './finance';

import {
  users,
  usersRelations,
  roleEnum,
  platformEnum,
  adminPermissionEnum,
} from './users';
import {
  otps,
  otpsRelations,
  sessions,
  sessionsRelations,
  oauthAccounts,
  oauthAccountsRelations,
  usedTokens,
  usedTokensRelations,
} from './auth';
import {
  clientAccounts,
  clientAccountsRelations,
  userStatusEnum,
  clientFavorites,
  clientFavoritesRelations,
  favoriteItemTypeEnum,
  clientWallets,
  clientWalletsRelations,
  clientWalletRecharges,
  clientWalletRechargesRelations,
  clientRechargeStatusEnum,
  clientTransactions,
  clientTransactionsRelations,
  clientTransactionTypeEnum,
  clientTransactionPurposeEnum,
} from './client';
import {
  expertAccounts,
  expertAccountsRelations,
  expertKycStatusEnum,
  specializations,
  specializationsRelations,
  professions,
  professionsRelations,
  professionSpecializations,
  professionSpecializationsRelations,
  expertSpecializations,
  expertSpecializationsRelations,
  expertProfessions,
  expertProfessionsRelations,
  expertConsultationPricing,
  expertConsultationPricingRelations,
  expertPricingTargetAudienceEnum,
  expertPricingStatusEnum,
  expertAstrologyServices,
  expertAstrologyServicesRelations,
  expertProducts,
  expertProductsRelations,
  expertProductRelationTypeEnum,
} from './expert';
import {
  products,
  productsRelations,
  productTypeEnum,
  productGroupEnum,
  productVariants,
  productVariantsRelations,
  carts,
  cartsRelations,
  cartItems,
  cartItemsRelations,
  orders,
  ordersRelations,
  orderStatusEnum,
  orderPaymentStatusEnum,
  orderItems,
  orderItemsRelations,
  orderItemStatusEnum,
  orderShipments,
  orderShipmentsRelations,
  shipmentStatusEnum,
  orderAddresses,
  orderAddressesRelations,
  orderAddressTypeEnum,
  orderPayments,
  orderPaymentsRelations,
  paymentTransactionStatusEnum,
  orderRefunds,
  orderRefundsRelations,
  refundDestinationEnum,
  refundStatusEnum,
  productCategories,
  productVariantPricing,
  productVariantPricingRelations,
  variantPricingAudienceEnum,
  variantPricingStatusEnum,
  productVariantMedia,
  productVariantMediaRelations,
  variantMediaRoleEnum,
  productVariantPromotions,
  productVariantPromotionsRelations,
  promotionDiscountTypeEnum,
  promotionAudienceEnum,
  productVariantFulfillment,
  productVariantFulfillmentRelations,
  fulfillmentTypeEnum,
  deliveryTypeEnum,
  productVariantInventory,
  productVariantInventoryRelations,
  coupons,
  couponsRelations,
  couponTypeEnum,
  couponStatusEnum,
  userCoupons,
  userCouponsRelations,
  wishlists,
  wishlistsRelations,
} from './commerce';
import {
  addresses,
  addressesRelations,
  addressTypeEnum,
  addressTagEnum,
} from './addresses';
import { media, mediaSourceEnum } from './media';
import {
  notifications,
  notificationsRelations,
  notificationTypeEnum,
  NotificationType,
} from './support';
import {
  callSessions,
  callSessionsRelations,
  callSessionStatusEnum,
  callSessionTypeEnum,
  chatSessions,
  chatSessionsRelations,
  chatSessionStatusEnum,
  chatMessages,
  chatMessagesRelations,
  chatMessageTypeEnum,
  consultationTopics,
  consultations,
  consultationsRelations,
  consultationsModeEnum,
  consultationsStatusEnum,
  consultationSessions,
  consultationSessionsRelations,
  consultationSessionsStatusEnum,
  consultationSessionsModeEnum,
  sessionProviders,
  sessionProvidersRelations,
  sessionRecordings,
  sessionRecordingsRelations,
  sessionRecordingsStatusEnum,
  consultationMessages,
  consultationMessagesRelations,
  consultationMessagesTypeEnum,
  consultationMessageAttachments,
  consultationMessageAttachmentsRelations,
  consultationBillings,
  consultationBillingsRelations,
  consultationBillingsStatusEnum,
  reviews,
  reviewsRelations,
} from './consultation';
import {
  merchantAccounts,
  merchantAccountsRelations,
  merchantStatusEnum,
  MerchantStatus,
} from './merchant';
import {
  wallets,
  walletsRelations,
  transactions,
  transactionsRelations,
  financeTransactionTypeEnum,
  financeTransactionPurposeEnum,
  withdrawals,
  withdrawalsRelations,
  withdrawalStatusEnum,
  idempotencyKeys,
  idempotencyKeysRelations,
  gatewayTransactions,
  gatewayTransactionsRelations,
  gatewayNameEnum,
  gatewayTransactionStatusEnum,
  gatewayIntentEnum,
  paymentOrders,
  paymentOrdersRelations,
  paymentOrderStatusEnum,
  commissionRules,
  commissionRulesRelations,
  commissionEventTypeEnum,
  commissionTypeEnum,
  commissionRateTypeEnum,
  commissionAppliesRoleEnum,
  commissionTiers,
  commissionTiersRelations,
  commissionSplits,
  commissionSplitsRelations,
  splitReferenceTypeEnum,
  earningPolicies,
  earningPoliciesRelations,
  earningEventTypeEnum,
  earningRateTypeEnum,
  earningAppliesRoleEnum,
  earningTiers,
  earningTiersRelations,
  earningSplits,
  earningSplitsRelations,
  generalLedger,
  generalLedgerEntryTypeEnum,
  generalLedgerPartyTypeEnum,
  generalLedgerEventTypeEnum,
} from './finance';

/**
 * Combined schema object for `drizzle(pool, { schema })`.
 * Aggregates all domain-dedicated schema tables and relations explicitly.
 */
export const schema = {
  // Users
  users,
  usersRelations,
  roleEnum,
  platformEnum,
  adminPermissionEnum,

  // Auth
  otps,
  otpsRelations,
  sessions,
  sessionsRelations,
  oauthAccounts,
  oauthAccountsRelations,
  usedTokens,
  usedTokensRelations,

  // Client
  clientAccounts,
  clientAccountsRelations,
  userStatusEnum,
  clientFavorites,
  clientFavoritesRelations,
  favoriteItemTypeEnum,
  clientWallets,
  clientWalletsRelations,
  clientWalletRecharges,
  clientWalletRechargesRelations,
  clientRechargeStatusEnum,
  clientTransactions,
  clientTransactionsRelations,
  clientTransactionTypeEnum,
  clientTransactionPurposeEnum,

  // Expert
  expertAccounts,
  expertAccountsRelations,
  expertKycStatusEnum,
  specializations,
  specializationsRelations,
  professions,
  professionsRelations,
  professionSpecializations,
  professionSpecializationsRelations,
  expertSpecializations,
  expertSpecializationsRelations,
  expertProfessions,
  expertProfessionsRelations,
  expertConsultationPricing,
  expertConsultationPricingRelations,
  expertPricingTargetAudienceEnum,
  expertPricingStatusEnum,
  expertAstrologyServices,
  expertAstrologyServicesRelations,
  expertProducts,
  expertProductsRelations,
  expertProductRelationTypeEnum,

  // Commerce
  products,
  productsRelations,
  productTypeEnum,
  productGroupEnum,
  productVariants,
  productVariantsRelations,
  carts,
  cartsRelations,
  cartItems,
  cartItemsRelations,
  orders,
  ordersRelations,
  orderStatusEnum,
  orderPaymentStatusEnum,
  orderItems,
  orderItemsRelations,
  orderItemStatusEnum,
  orderShipments,
  orderShipmentsRelations,
  shipmentStatusEnum,
  orderAddresses,
  orderAddressesRelations,
  orderAddressTypeEnum,
  orderPayments,
  orderPaymentsRelations,
  paymentTransactionStatusEnum,
  orderRefunds,
  orderRefundsRelations,
  refundDestinationEnum,
  refundStatusEnum,
  productCategories,
  productVariantPricing,
  productVariantPricingRelations,
  variantPricingAudienceEnum,
  variantPricingStatusEnum,
  productVariantMedia,
  productVariantMediaRelations,
  variantMediaRoleEnum,
  productVariantPromotions,
  productVariantPromotionsRelations,
  promotionDiscountTypeEnum,
  promotionAudienceEnum,
  productVariantFulfillment,
  productVariantFulfillmentRelations,
  fulfillmentTypeEnum,
  deliveryTypeEnum,
  productVariantInventory,
  productVariantInventoryRelations,
  coupons,
  couponsRelations,
  couponTypeEnum,
  couponStatusEnum,
  userCoupons,
  userCouponsRelations,
  wishlists,
  wishlistsRelations,

  // Addresses
  addresses,
  addressesRelations,
  addressTypeEnum,
  addressTagEnum,

  // Media
  media,
  mediaSourceEnum,

  // Support
  notifications,
  notificationsRelations,
  notificationTypeEnum,
  NotificationType,

  // Consultation
  callSessions,
  callSessionsRelations,
  callSessionStatusEnum,
  callSessionTypeEnum,
  chatSessions,
  chatSessionsRelations,
  chatSessionStatusEnum,
  chatMessages,
  chatMessagesRelations,
  chatMessageTypeEnum,
  consultationTopics,
  consultations,
  consultationsRelations,
  consultationsModeEnum,
  consultationsStatusEnum,
  consultationSessions,
  consultationSessionsRelations,
  consultationSessionsStatusEnum,
  consultationSessionsModeEnum,
  sessionProviders,
  sessionProvidersRelations,
  sessionRecordings,
  sessionRecordingsRelations,
  sessionRecordingsStatusEnum,
  consultationMessages,
  consultationMessagesRelations,
  consultationMessagesTypeEnum,
  consultationMessageAttachments,
  consultationMessageAttachmentsRelations,
  consultationBillings,
  consultationBillingsRelations,
  consultationBillingsStatusEnum,
  reviews,
  reviewsRelations,

  // Merchant
  merchantAccounts,
  merchantAccountsRelations,
  merchantStatusEnum,
  MerchantStatus,

  // Finance - Wallet
  wallets,
  walletsRelations,
  transactions,
  transactionsRelations,
  financeTransactionTypeEnum,
  financeTransactionPurposeEnum,
  withdrawals,
  withdrawalsRelations,
  withdrawalStatusEnum,
  idempotencyKeys,
  idempotencyKeysRelations,

  // Finance - Payments
  gatewayTransactions,
  gatewayTransactionsRelations,
  gatewayNameEnum,
  gatewayTransactionStatusEnum,
  gatewayIntentEnum,
  paymentOrders,
  paymentOrdersRelations,
  paymentOrderStatusEnum,

  // Finance - Commissions
  commissionRules,
  commissionRulesRelations,
  commissionEventTypeEnum,
  commissionTypeEnum,
  commissionRateTypeEnum,
  commissionAppliesRoleEnum,
  commissionTiers,
  commissionTiersRelations,
  commissionSplits,
  commissionSplitsRelations,
  splitReferenceTypeEnum,

  // Finance - Earnings
  earningPolicies,
  earningPoliciesRelations,
  earningEventTypeEnum,
  earningRateTypeEnum,
  earningAppliesRoleEnum,
  earningTiers,
  earningTiersRelations,
  earningSplits,
  earningSplitsRelations,

  // Finance - Ledger
  generalLedger,
  generalLedgerEntryTypeEnum,
  generalLedgerPartyTypeEnum,
  generalLedgerEventTypeEnum,
};
